[docker_hosts:children]
nginx_servers
httpd_servers
mysql_servers

[httpd_servers]
dockerhost_1 ansible_ssh_host='192.168.0.1' http_port='8081'
dockerhost_2 ansible_ssh_host='192.168.0.2' http_port='8082'

[mysql_servers]
dockerhost_1 ansible_ssh_host='192.168.0.1'

[nginx_servers]
dockerhost_2 ansible_ssh_host='192.168.0.2'
